version: '3.8'
services:
  cache:
    image: redis:6.2.7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "henrique@poc.com"
      PGADMIN_DEFAULT_PASSWORD: "admin!"
    depends_on:
      - db
    ports:
      - '8081:80'

volumes:
  cache:
    driver: local
  db:
    driver: local
